### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by magnub** [kanawish/android-mvi-sample#5]
404: http://hannesdorfmann.com/android/player-view-intent
404: https://cycle.js.org/player-view-intent.html
404: http://thenewstack.io/developers-need-know-mvi-player-view-intent/

**Comment by kanawish** [comment]
Refactoring gone wild! `model` somehow got replaced by `player`. I'll fix it, thanks for pointing this out!

**Comment by nodir96** [comment]
ComposedException 1 :
    	java.lang.IllegalStateException: editorIntent encountered an inconsistent State. [Looking for class uz.cap.loginpagemvi.model.AnotherLoginPageState$Loading but was class uz.cap.loginpagemvi.model.AnotherLoginPageState$Default]
W/System.err:     at uz.cap.loginpagemvi.intent.LoginPageIntentFactory$Companion$buildCheckLoginState$$inlined$editorIntent$1.invoke(LoginPageIntentFactory.kt:32)
        at uz.cap.loginpagemvi.intent.LoginPageIntentFactory$Companion$buildCheckLoginState$$inlined$editorIntent$1.invoke(LoginPageIntentFactory.kt:24)
        at uz.cap.loginpagemvi.intent.IntentKt$intent$1.reduce(Intent.kt:9)
        at uz.cap.loginpagemvi.model.ModelStore$store$1.apply(ModelStore.kt:15)
W/System.err:     at uz.cap.loginpagemvi.model.ModelStore$store$1.apply(ModelStore.kt:9)
        at io.reactivex.internal.operators.observable.ObservableScanSeed$ScanSeedObserver.onNext(ObservableScanSeed.java:98)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by nodir96** [comment]
@kanawish Hi. I'm learning MVI pattern from you tutorial, but I have a problem like this 
When i changed state there are ...
 ComposedException 1 :
    	java.lang.IllegalStateException: editorIntent encountered an inconsistent State. [Looking for class uz.cap.loginpagemvi.model.AnotherLoginPageState$Loading but was class uz.cap.loginpagemvi.model.AnotherLoginPageState$Default]
W/System.err:     at uz.cap.loginpagemvi.intent.LoginPageIntentFactory$Companion$buildCheckLoginState$$inlined$editorIntent$1.invoke(LoginPageIntentFactory.kt:32)
        at uz.cap.loginpagemvi.intent.LoginPageIntentFactory$Companion$buildCheckLoginState$$inlined$editorIntent$1.invoke(LoginPageIntentFactory.kt:24)
        at uz.cap.loginpagemvi.intent.IntentKt$intent$1.reduce(Intent.kt:9)
        at uz.cap.loginpagemvi.model.ModelStore$store$1.apply(ModelStore.kt:15)
W/System.err:     at uz.cap.loginpagemvi.model.ModelStore$store$1.apply(ModelStore.kt:9)
        at io.reactivex.internal.operators.observable.ObservableScanSeed$ScanSeedObserver.onNext(ObservableScanSeed.java:98)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
